### ISSUE TITLE
Error org.hsqldb.HsqlException (database w/ docker)

### ISSUE THREAD

**Issue by bonnebulle** [airsonic-advanced/airsonic-advanced#1025]
Hey
installing  airsonic-advanced 
my docker-compose.yaml :
```yaml
---
version: "2.1"
services:
  airsonic_new:
#    image: lscr.io/linuxserver/airsonic
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic
    environment:
      - PUID=33
      - PGID=33
      - TZ=Europe/Paris
#      - JAVA_OPTS=<options> #optional
    volumes:
      - /path/config:/config
      - /path/music:/music
      - /path/___Playlists/:/playlists
      - /path/___Podcasts/:/podcasts
    ports:
      -  8112:4040
    devices:
      - /dev/snd:/dev/snd #optional
    restart: unless-stopped
```

I have this log error...
`org.hsqldb.HsqlException: wrong database file version: unsupported old database version`

Thanks for developing
am ready to debug
