### ISSUE TITLE
DOCKER /var/airsonic/ Cannot be located on mounted drive due to symlinks being used

### ISSUE THREAD

**Issue by laundmo** [airsonic-advanced/airsonic-advanced#340]
# Workaround

Make sure the volume for /var/airsonic is not located on a mounted drive, since symlinks dont work in that case

## Problem description

airsonic-advanced container does not start becuse of ln issue
i have attempted to change the PUID and PGID to 1001 and to mount the ffmpeg binary as a volume on the location in the error.

```
Docker USER id: 0
Docker PUID env: 0
Docker USER group: 0
Docker PGID env: 0
usermod: no changes
Process will run as:
User: 0
Group: 0
ln: failed to create symbolic link '/var/airsonic/transcode/ffmpeg': Operation not supported
```
### Steps to reproduce

this is run with docker compose, so you would need that installed.

my docker compose config
```yaml
services:
 airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic
    ports:
      - "127.0.0.1:4040:4040"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /usr/bin/ffmpeg:/var/airsonic/transcode/ffmpeg
      - /mnt/data/airsonic/config:/var/airsonic
      - /mnt/data/lidarr/downloads:/var/music
      - /mnt/data/airsonic/playlists:/var/playlists
      - /mnt/data/airsonic/podcasts:/var/podcasts
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
```

then use `docker-compose --compatibility  up -d` to start it

## System information

 * **Airsonic version**: airsonicadvanced/airsonic-advanced:latest (doesn't start, cant see about page)
 * **Operating system**: Ubuntu 18.04.3 LTS
 * **Java version**: Whatever the docker comes with
 * **Proxy server**: Nginx
 * **Client**: none, doesn't start
 * **Language**: none, doesn't start
* **Docker Version**: Docker version 19.03.4, build 9013bf583a
