### ISSUE TITLE
airsonic vanilla to advanced migration in docker ->java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by lbesnard** [airsonic-advanced/airsonic-advanced#367]
## Problem description
I'm trying to test airsonic-advanced from my existing airsonic config. The new features seem appealing as well as the active dev; However, advanced crashed during the database migration.

### Steps to reproduce

1. stop working version of airsonic vanilla in docker
2. Shutdown airsonic vanilla docker container
3. ```cp``` config directory of airsonic vanilla docker container into new airsonic-advanced container (i tried editing the db file with ```sed``` to point to the new mount points, but that didn't change the issue)
4. start new airsonic-advanced container


```
2020-09-09T08:40:09.334135957Z LOGBACK: No context given for c.q.l.core.rolling.SizeAndTimeBasedRollingPolicy@1571967156
2020-09-09T08:40:09.571118198Z            _                       _          
2020-09-09T08:40:09.571174088Z      /\   (_)                     (_)         
2020-09-09T08:40:09.571184253Z     /  \   _ _ __  ___  ___  _ __  _  ___     
2020-09-09T08:40:09.571193350Z    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|    
2020-09-09T08:40:09.571202375Z   / ____ \| | |   \__ \ (_) | | | | | (__     
2020-09-09T08:40:09.571211453Z  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|    
2020-09-09T08:40:09.571220537Z                                                
2020-09-09T08:40:09.571229342Z                         11.0.0-SNAPSHOT
2020-09-09T08:40:09.571238224Z 
2020-09-09T08:40:09.571246619Z 
2020-09-09T08:40:09.571279002Z 
2020-09-09T08:40:12.689361700Z 2020-09-09 18:40:12.664  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 1.8.0 to 2.5
2020-09-09T08:40:31.841652876Z 2020-09-09 18:40:31.834  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/db.backup.20200909184012
2020-09-09T08:42:22.461072224Z 
2020-09-09T08:42:22.461132672Z Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "mysql-cj-abandoned-connection-cleanup"
```


I'm sure this is a matter of adding the right java environment variable. I tried in my docker compose file to add the following line in the environment part of the container, however I have the same issue
```     
 - JVM_OPTS=-Xmx2g -Xms2g -XX:MaxPermSize=1024m                                                                                                                                                                                         
```
## System information

 * **Airsonic version**: latest docker version (as of 9 Sept 2020)
 * **Operating system**: docker on debian jessie
 * **Java version**: *the Java version you are using to run Airsonic.*


## Additional notes
```yaml
###########################################                                                                                                                                                                                                  
  airsonic:                                                                                                                                                                                                                                  
    image: linuxserver/airsonic:latest                                                                                                                                                                                                       
    container_name: airsonic                                                                                                                                                                                                                 
    environment:                                                                                                                                                                                                                             
      - PUID=1000                                                                                                                                                                                                                            
      - PGID=1000                                                                                                                                                                                                                            
      - TZ=${TZ}                                                                                                                                                                                                                             
    volumes:                                                                                                                                                                                                                                 
      - $DOCKER_CONFIG_PATH/airsonic:/config                                                                                                                                                                                                 
      - $MUSIC_PATH:/music:ro                                                                                                                                                                                                                
      - $PLAYLISTS_PATH:/playlists                                                                                                                                                                                                           
      - $PODCASTS_PATH:/podcasts                                                                                                                                                                                                             
    ports:                                                                                                                                                                                                                                   
      - 8080:4040                                                                                                                                                                                                                            
    restart: unless-stopped                                                                                                                                                                                                                  
########################                                                                                                                                                                                                                     
# airsonic advanced                                                                                                                                                                                                                          
  airsonic-advanced:                                                                                                                                                                                                                         
    image: airsonicadvanced/airsonic-advanced:latest                                                                                                                                                                                         
    container_name: airsonic-advanced                                                                                                                                                                                                        
    environment:                                                                                                                                                                                                                             
      - PUID=1000                                                                                                                                                                                                                            
      - PGID=1000                                                                                                                                                                                                                            
      - TZ=${TZ}                                                                                                                                                                                                                             
    volumes:                                                                                                                                                                                                                                 
      - $DOCKER_CONFIG_PATH/airsonic-advanced:/var/airsonic                                                                                                                                                                                  
      - $MUSIC_PATH:/var/music:ro                                                                                                                                                                                                            
      - $PLAYLISTS_PATH:/var/playlists                                                                                                                                                                                                       
      - $PODCASTS_PATH:/var/podcasts                                                                                                                                                                                                         
    ports:                                                                                                                                                                                                                                   
      - 8081:4040                                                                                                                                                                                                                            
    restart: unless-stopped                             
```
