### ISSUE TITLE
Airsonic Advance not playing ANY songs when Airsonic plain works fine

### ISSUE THREAD

**Issue by Cytomax55** [airsonic-advanced/airsonic-advanced#496]
## Problem description

11.0.0-SNAPSHOT.20210226210819 – February 26, 2021 at 4:08:19 PM EST

### Steps to reproduce

Docker version 10.6.2-RELEASE – May 3, 2020 works perfectly fine with mp3 and .opus files

I made a new directory "airsonic" 
I made 4 sub directories "data, music, playlists, podcasts"

```
airsonic:
    #image: airsonic/airsonic
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic
    environment:      
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      #- /media/username/nfsset/containers/airsonic/data:/airsonic/data
      - /media/username/nfsset/containers/airsonic/data:/var/airsonic
      
      #- /media/username/nfsset/containers/airsonic/music:/airsonic/music
      - /media/username/nfsset/containers/airsonic/music:/var/music
      
      #- /media/username/nfsset/containers/airsonic/playlists:/airsonic/playlists
      - /media/username/nfsset/containers/airsonic/playlists:/var/playlists
      
      #- /media/username/nfsset/containers/airsonic/podcasts:/airsonic/podcasts
      - /media/username/nfsset/containers/airsonic/podcasts:/var/podcasts
      
      - /media/username/smbshare/Music/:/media/eddie/smbshare/Music
    ports:
      - 4040:4040
    restart: unless-stopped
```

I can see ALL my music but i cant play any of it

Here are the chrome logs as requested

[airsonic.com-1614402520315.log](https://github.com/airsonic-advanced/airsonic-advanced/files/6053772/airsonic.com-1614402520315.log)

Airsonic logs
[airsonic.log](https://github.com/airsonic-advanced/airsonic-advanced/files/6053758/airsonic.log)

## System information

Airsonic version: 11.0.0-SNAPSHOT.20210226210819 – February 26, 2021 at 4:08:19 PM EST
Operating system: Manjaro Linux is host OS > docker container from airsonic/airsonic
Java version: docker container from airsonic/airsonic
Proxy server: docker container from linuxserver/swag
Client: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
Language: English

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*
