### ISSUE TITLE
Problems with using Docker & Traefik as reverse proxy

### ISSUE THREAD

**Issue by Uatschitchun** [airsonic-advanced/airsonic-advanced#508]
## Problem description

I've set up Airsonic advanced (AA) with :latest docker image and am using traefik as reverse proxy. The web page doesn't load fully and "Settings" menu can't be opened at all. The page loads and shows covers if I click on start and the settings page loads if I open it in a new tab.

### Steps to reproduce

This is my docker-compose.yml:
```
version: '2'

services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    restart: always
    ports:
      - 4040:4040
    networks:
      - web
      - default
    volumes:
      - Airsonic-advanced/data/:/var/airsonic/
      - mp3/:/var/music
      - playlists:/var/playlists
      -Podcasts/:/var/podcasts
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native
      - JAVA_OPTS=-Xmx1536m
    labels:
      - "traefik.enable=true"
      - "traefik.backend=airsonic"
      - "traefik.frontend.rule=Host:airsonic.myserver.dns.org"
      - "traefik.port=4040"
      - "traefik.docker.network=web"
      - "traefik.protocol=http"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.SSLForceHost=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.SSLHost=myserver.dns.org"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      - "traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.frontend.headers.customResponseHeaders: Feature-Policy:camera 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none'; payment 'none'; speaker 'none'; usb 'none'; vibrate 'none'; vr 'none';"
      - "traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"

networks:
  web:
    external: true
```

Could be I've setup the **labels** wrong or am missing some?!

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210309214438
 * **Operating system**: Docker airsonicadvanced/airsonic-advanced:latest
 * **Proxy server**: Docker traefik:v1.7
 * **Client**: Opera, Firefox

## Additional notes

Am willing to provide logs if you tell what's needed. Can't find anything special in them and think it's a reverse proxy problem
