### ISSUE TITLE
Can't create directory '/var/airsonic/transcode'

### ISSUE THREAD

**Issue by jwillmer** [airsonic-advanced/airsonic-advanced#513]
## Problem description

I get the following error: `can't create directory '/var/airsonic/transcode'`

### Steps to reproduce

Part of my docker-compose:

```
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native
    volumes:
      - ${FILE_LOCATION}/media/airsonic-advanced/config:/var/airsonic/config/db
      - /media/Music:/var/music
```

## Additional notes

When I map the whole `/var/airsonic` it works but I would like to only store the database on a persistent storage.

**Comment by jwillmer** [comment]
Related issue: https://github.com/airsonic-advanced/airsonic-advanced/issues/157

**Comment by qwertyAcabtino** [comment]
I hit the same problem in the past.
In the end, the problem got solved on its own by realizing that actually, persisting the airsonic data is not needed since all the configuration needed at boot is given by either the env vars or the persisted data in a external database.
So, you can walk over this problem by not mapping such folder. Sounds like an easy solution, but actually makes the app even more stateless, so a bit more container friendly.

This is the docker-compose I use atm: https://github.com/qwertyAcabtino/airsonic-advance-docker-compose-external-db/blob/main/docker-compose.yml

**Comment by jwillmer** [comment]
I thought about it but I like the separation of my apps. if all are in one dB then I have a single place if failures

**Comment by LeducH** [comment]
I have the same issue using 

```
version: '3.3'
services:
    airsonic-advanced:
        volumes:
            - '/mnt/shared/Media/Music:/var/music'
            - '/mnt/shared/AppData/airsonic-advanced/data:/var/data'
            - '/mnt/shared/AppData/airsonic-advanced/playlists:/airsonic/playlists'
            - '/mnt/shared/AppData/airsonic-advanced/podcasts:/airsonic/podcasts'
        image: 'airsonicadvanced/airsonic-advanced:latest'
        environment:
          #- CONTEXT_PATH=/airsonic
          - TZ=<>
          - PUID=1000
          - PGID=984
        ports:
            - '4042:4040'
        restart: unless-stopped

```

error message 

```
airsonic-advanced_1  | Docker PGID env: 984
airsonic-advanced_1  | usermod: no changes
airsonic-advanced_1  | Process will run as:
airsonic-advanced_1  | User: 1000
airsonic-advanced_1  | Group: 984
airsonic-advanced_1  | mkdir: cannot create directory ‘/var/airsonic/transcode’: Permission denied
airsonic-advanced_1  | Docker USER id: 0
airsonic-advanced_1  | Docker PUID env: 1000
airsonic-advanced_1  | Docker USER group: 0
airsonic-advanced_1  | Docker PGID env: 984
airsonic-advanced_1  | usermod: no changes
airsonic-advanced_1  | Process will run as:
airsonic-advanced_1  | User: 1000
airsonic-advanced_1  | Group: 984
airsonic-advanced_1  | mkdir: cannot create directory ‘/var/airsonic/transcode’: Permission denied
airsonic-advanced_1  | Docker USER id: 0
airsonic-advanced_1  | Docker PUID env: 1000
airsonic-advanced_1  | Docker USER group: 0
airsonic-advanced_1  | Docker PGID env: 984
airsonic-advanced_1  | usermod: no changes
airsonic-advanced_1  | Process will run as:
airsonic-advanced_1  | User: 1000
airsonic-advanced_1  | Group: 984
airsonic-advanced_1  | mkdir: cannot create directory ‘/var/airsonic/transcode’: Permission denied
airsonic-advanced_1  | Docker USER id: 0
airsonic-advanced_1  | Docker PUID env: 1000
airsonic-advanced_1  | Docker USER group: 0
airsonic-advanced_1  | Docker PGID env: 984
airsonic-advanced_1  | usermod: no changes
airsonic-advanced_1  | Process will run as:
airsonic-advanced_1  | User: 1000
airsonic-advanced_1  | Group: 984
airsonic-advanced_1  | mkdir: cannot create directory ‘/var/airsonic/transcode’: Permission denied
```

what is the official command for docker-compose deployment?
