### ISSUE TITLE
Unable to deploy docker image as root or non-root user due to permissions failures

### ISSUE THREAD

**Issue by ackstorm23** [airsonic-advanced/airsonic-advanced#574]
## Problem description

If I try to deploy the latest docker image, it fails to start and exits with return code 1 due to permissions issues.  This happens both with root user or non-root user, although not for the reason.

### Steps to reproduce

Attempt to deploy a docker image with root user default and the following docker-compose.yml

```
version: '2'
services:
  airsonic:
    image: airsonicadvanced/airsonic-advanced
    restart: unless-stopped

    environment:
      - TZ=US/Central
    cap_drop:
      - ALL
    volumes:
      - /nfs/audio:/media:ro
```

```
[root@host airsonic-advanced]# docker-compose up
Creating airsonic-advanced_airsonic_1 ... done
Attaching to airsonic-advanced_airsonic_1
airsonic_1  | Docker USER id: 0
airsonic_1  | Docker PUID env: 0
airsonic_1  | Docker USER group: 0
airsonic_1  | Docker PGID env: 0
airsonic_1  | usermod: no changes
airsonic_1  | error: failed switching to "root": operation not permitted
```
Attempt to deploy a docker image with non-root uid and gid and the following docker-compose.yml

```
version: '2'
services:
  airsonic:
    image: airsonicadvanced/airsonic-advanced
    restart: unless-stopped

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
    cap_drop:
      - ALL
    volumes:
      - /nfs/nfs_audio:/media:ro
```

```
[root@host airsonic-advanced]# docker-compose up
Recreating airsonic-advanced_airsonic_1 ... done
Attaching to airsonic-advanced_airsonic_1
airsonic_1  | Docker USER id: 0
airsonic_1  | Docker PUID env: 1000
airsonic_1  | Docker USER group: 0
airsonic_1  | Docker PGID env: 1000
airsonic_1  | groupadd: failure while writing changes to /etc/gshadow
airsonic-advanced_airsonic_1 exited with code 1
```

## System information

 * **Airsonic version**: *airsonicadvanced/airsonic-advanced    latest   4ddadb4ad90b   29 hours ago    963MB*
 * **Operating system**: *Arch Linux with kernel 5.11.11-arch1-1*
 * **Docker Version**: *Docker version 20.10.5, build 55c4c88966*
 * **Java version**: *not applicable/provided by docker image*
 * **Proxy server**: *none*
 * **Client**: *not applicable*
 * **Language**: *not applicable*

## Additional notes

1. I am able to launch other containers without any permissions issues, including the traditional airsonic docker images. 
2. I have tried deploying both as the root user and as a non-root user with the docker group, no difference
3. I have also tried with only the PGID and no PUID listed, no luck
4. I have also tried with the PUID and PGID both listed a 0, no luck
