### ISSUE TITLE
Deploy with external postgres database using docker-compose  

### ISSUE THREAD

**Issue by LeducH** [airsonic-advanced/airsonic-advanced#591]
## Problem description

There is no information how deploy `airsonic-advanced` with external postgres database with docker compose  

### Steps to reproduce

Check the readme. 
try to find instructions how to deploy `airsonic-advanced` with docker compose and a external postgres sql 

## System information

 * **Airsonic version**: lates
 * * **Operating system**: *arch*
 * **Java version**: *dockerimage*
 * **Proxy server**: *none*
 * **Client**: *firefox/chromium*
 * **Language**: *EN*

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by randomnicode** [comment]
There is some information on the [vanilla airsonic documentation](https://airsonic.github.io/docs/database/) about external dbs, however admittedly this does not say anything about docker-centric setups. Additionally this is further muddied by the fact that several property names have changed or are obsolete (as described in the [github README](https://github.com/airsonic-advanced/airsonic-advanced#11x-series)).

Perhaps the community can share their sample docker-compose files?

**Comment by randomnicode** [comment]
Perhaps this might suffice?

```
version: "3.9"
   
services:
  db:
    image: postgres:latest
    volumes:
      - /host/path/to/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    env:
      - spring_datasource_url: 'jdbc:postgresql://db:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
      - spring_datasource_username: postgres
      - spring_datasource_password: postgres
      - spring_liquibase_parameters_userTableQuote: '"'
    volumes:
      - /host/path/to/my/music:/var/music
      - /host/path/to/my/podcasts:/var/podcasts
      - /host/path/to/my/playlists:/var/playlists
      - /host/path/to/airsonic/data:/var/airsonic
    ports:
      - "4040:4040"
    depends_on:
      - db

```
