### ISSUE TITLE
MIssing music

### ISSUE THREAD

**Issue by uSlackr** [airsonic-advanced/airsonic-advanced#614]
## Problem description
(I realize this is a problem of my stupidity, but I do not know how to fix it. ) I started my airsonic-adv container with the music volume off-line.  I fixed the problem and restarted the container, but airsonic will not index all the music files.  It has currently found 16,089 of some 24,000 music files (flac, mp3, wma).  I have verified that missing files are on disk.
What I've tried:
- start a full scan (many times)
- Clean the database
- searching for artists and clicking through on an album - this is the only action that add music to the index.

### Steps to reproduce
shutdown docker host
Power off external storage
Start host and Airsonic-Adv container

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210815234208 – August 15, 2021 at 7:42:08 PM EDT
 * **Operating system**: Debian 10.10 & docker 20.10.8

 * **Java version**: docker
 * **Proxy server**: swag latest (ghcr.io/linuxserver/swag)
 *
   
 * **Client**: Edge (Chromium  93)
 * **Language**: Eng - us

**Comment by randomnicode** [comment]
because the airsonic data files (including the db) is contained on an ephemeral volume, it does not get preserved across reboots. you should attach a persistent volume to the data directory so that your data is persisted across reboots
-v /<datadir>:/var/airsonic

**Comment by uSlackr** [comment]
I believe I've already done that.  Here is my docker compose snippet:
```
  airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    container_name: airsonic
    user: "1000"
    # links:
    #   - swag 
    depends_on:
      - swag
    environment:
      - TZ=America/New_York # e.g. Europe/London
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      # - JAVA_OPTS   #= "-DXmm300m" # For passing additional java options.
      # - CONTEXT_PATH # For setting url-base in reverse proxy setups.
    volumes:
      - /mnt/samba/Music/podcasts:/var/podcasts # Location of podcasts.
      - /mnt/samba/Music/playlists:/var/playlists # Location for playlists to be saved to.
      - /mnt/samba/Music:/var/music # Location of music.
      - /mnt/samba/TV:/var/media # Location of other media.
      - /data/airsonic:/var/airsonic # Configuration file location.

    ports:
      - 4040:4040 # WebUI
      - 4041:4041 # UPNP
```
