### ISSUE TITLE
docker hub doc enhancement

### ISSUE THREAD

**Issue by nopoz** [airsonic-advanced/airsonic-advanced#620]
The [docker hub documentation](https://hub.docker.com/r/airsonicadvanced/airsonic-advanced) could be a bit easier to follow for those less familar with docker. Below is a docker-compose and docker run example that could expand on the existing documentation. 

`docker-compose.yml` file example:

```
version: "3"

services:

  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    ports: 
      - 4040:4040
    user: pid:gid #optional - run container as user
    environment:
      - TZ=America/Los_Angeles #optional - show logs in local timezone
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native #optional - if you use a reverse-proxy
    volumes:
      - /host/path/to/my/playlists:/var/playlists
      - /host/path/to/my/podcasts:/var/podcasts
      - /host/path/to/my/data:/var/airsonic
      - /host/path/to/my/music:/var/music
```

`docker run` example - expanded to include other useful env variables:

```
docker run -d \
    --user pid:gid \
    --name airsonic-advanced \
    -e TZ=America/Los_Angeles \
    -e JAVA_OPTS=-Dserver.forward-headers-strategy=native \
    -p 4040:4040 \
    -v /host/path/to/my/music:/var/music \
    -v /host/path/to/my/podcasts:/var/podcasts \
    -v /host/path/to/my/playlists:/var/playlists \
    -v /host/path/to/my/data:/var/airsonic \
    --restart unless-stopped \
    airsonicadvanced/airsonic-advanced:latest
```
