### ISSUE TITLE
What is admin login docker? How do you create a user with docker deployment?

### ISSUE THREAD

**Issue by LeducH** [airsonic-advanced/airsonic-advanced#660]
## Problem description

There is no information on what the first log in user is

### Steps to reproduce

use attached docker compose 
go to localhost:4042 
try to log on 

## System information

```
version: "3"

services:
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    ports:
      - 4042:4040
      - 4043:4041 #UPnp
        #    user: pid:gid #optional - run container as user
    environment:
      - TZ=Europe/Berlin #optional - show logs in local timezone
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native #optional - if you use a reverse-proxy
    volumes:
      - /mnt/shared/Media/Music:/var/music
      - /mnt/shared/AppData/airsonic-advanced/data:/var/data
      - /mnt/shared/AppData/airsonic-advanced/playlists:/airsonic/playlists
      - /mnt/shared/AppData/airsonic-advanced/podcasts:/airsonic/podcasts
```

## Additional notes
 
how do you set a admin user??
