### ISSUE TITLE
UPnPService error results in restart loop

### ISSUE THREAD

**Issue by fkrivsky** [airsonic-advanced/airsonic-advanced#676]
## Problem description

After a clean setup (no previous data), the application starts and I can set it up and start scanning folders.

However, the next day the app is not starting up, with this error in the logs: 
``2021-11-29 21:22:05.842  WARN --- ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'DLNASettingsController': Unsatisfied dependency expressed through field 'upnpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'UPnPService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Shutdown in progress
``
### Steps to reproduce

1. *Have a clean slate - the data dir to be mounted to /var/airsonic is empty*
2. *Start the airsonic-advanced container as `docker stack deploy -c filename.yml stackname`*
3. *Set up the basics - change admin pwd, add user, set media folder, start library scan.*
4. *Do NOT enable DLNA service*
5. *Wait till next day*
6. *Now, the container is in a restart loop, with the aforementioned error as the last message*

## System information

 * **Airsonic version**: Inaccessible now, 
 * **Operating system**:  Ubuntu Server 20.04, Docker 20.10.11,
 * **Java version**: default in the official docker image
 * **Proxy server**: Nginx
 * **Client**: chrome/vivaldi
 * **Language**: default

## Additional notes

Deployed in Docker Swarm with the following compose file:
```
version: "3"
services:
  airsonic:
    image: airsonicadvanced/airsonic-advanced:latest
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
      - JAVA_OPTS="-Dserver.forward-headers-strategy=native"
    volumes:
      - /mnt/data/music:/var/music
      - /mnt/data/music/Podcasts:/var/podcast
      - /mnt/data/music/Playlists:/var/playlists
      - /mnt/config/a-advanced:/var/airsonic
    ports:
      - 4448:4040
```
