### ISSUE TITLE
Getting DNLA to work in Docker

### ISSUE THREAD

**Issue by beardedfool** [airsonic-advanced/airsonic-advanced#681]
Bit lost trying to get DNLA working on the docker:latest using ports. It's not detected from other devices

It does seem to work if you set
`network_mode: "host"`

I've tried setting it with 
```
    environment:
      - UPnpPort=4041
```

Am I misunderstaning this, should it go in a a JAVA_OPTS?

Can I confirm that the LAN Server address in DNLA settings should be the web 
e.g. http://music:4040/
rather than the UPnp http://music:4041/

nmap is showing the ports as open on the host (closed when docker not running)

Interestingly changin the UPnpPort doesn't seem that change it in the docker

```
version: "3"

services:
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    ports: 
      - 4040:4040
      - 4044:4044 #UPnp
      - 1900:1900 # DNLA
    user: 1207:1207
    environment:
      - TZ=Europe/London #optional - show logs in local timezone
      # https://airsonic.github.io/docs/configure/airsonic-properties/
      - UPnpPort=4044
      # - JAVA_OPTS=-Dserver.forward-headers-strategy=native #optional - if you use a reverse-proxy
    volumes:
      - /home/docker/airsonic/playlists:/var/playlists
      - /home/docker/airsonic/podcasts:/var/podcasts
      - /home/docker/airsonic/data:/var/airsonic
```

Gives 

```
airsonic-advanced    | 2021-12-02 13:16:34.736  INFO --- o.a.player.service.UPnPService           : Starting UPnP service...
airsonic-advanced    | 2021-12-02 13:16:34.753  INFO --- o.a.player.service.UPnPService           : Successfully started UPnP service on port 4041!
airsonic-advanced    | 2021-12-02 13:16:34.791  INFO --- o.a.player.service.UPnPService           : Enabling UPnP/DLNA media server
```

Is this relevant?
https://github.com/airsonic/airsonic/pull/1380
