### ISSUE TITLE
Help getting Jukebox working on Docker

### ISSUE THREAD

**Issue by DeadEnded** [airsonic-advanced/airsonic-advanced#696]
## Problem description

After spinning up docker container - I can't get the jukebox to work.
I have added environmental variables, mapped `sound.parameters` - so far I haven't  been able to get it working.

### Steps to reproduce

1. Install in docker as a container - change the default web player to be jukebox.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211208080314
 * **Operating system**: Docker version 20.10.11, Ubuntu 21.04
 * **Java version**: Whatever comes with the container :-) openjdk 14.0.2 2020-07-14
 * **Proxy server**: None
 * **Client**: FireFox 95.0 
 * **Language**: English

## Additional notes

Docker-Compose:

```
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:latest
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
    networks:
      DockerLAN:
        ipv4_address: x.x.x.x #(redacted)
    ports: 
      - 4040:4040
      - 4041:4041 #UPnp
    user: 1000:1000 #optional - run container as user
    environment:
      - JAVA_OPTS="-Djavax.sound.sampled.Clip=#USB [plughw:1,0] -Djavax.sound.sampled.Port=#Port USB [hw:1] -Djavax.sound.sampled.SourceDataLine=#USB [plughw:1,0] -Djavax.sound.sampled.TargetDataLine=#USB [plughw:1,0]"
    volumes:
      - /docker/airsonic/playlists:/var/playlists
      - /docker/airsonic/podcasts:/var/podcasts
      - /docker/airsonic:/var/airsonic
      - /docker/airsonic/sound.parameters:/usr/lib/jvm/java-14.0.2-openjdk/jre/lib/sound.properties #Believe this is the correct path
      - /media/elements/music:/var/music
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

audioDevList.java results:
```
# javac audioDevList.java
# java audioDevList
Available mixers:
Port Generic [hw:0]
Port USB [hw:1]
Port Generic_1 [hw:2]
Generic [plughw:0,3]
Generic [plughw:0,7]
Generic [plughw:0,8]
Generic [plughw:0,9]
USB [plughw:1,0]
Generic_1 [plughw:2,0]
Generic_1 [plughw:2,1]
Generic_1 [plughw:2,2]
```

sounds.parameters files contents:
```
javax.sound.sampled.Clip=#USB [plughw:1,0]
javax.sound.sampled.Port=#Port USB [hw:1]
javax.sound.sampled.SourceDataLine=#USB [plughw:1,0]
javax.sound.sampled.TargetDataLine=#USB [plughw:1,0]
```

My server has a USB JabraSpeak 510 attached.
This is what I am trying to use as the jukebox speaker.

Checked logs and see this:
`java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, big-endian is supported.`

I've tried to identify what formats my speaker supports to see if that is the problem - but I haven't been able to get past this error.

Thanks for any help!
DeadEnd
