### ISSUE TITLE
Playlist losing connection to songs "Missing"

### ISSUE THREAD

**Issue by tw1015** [airsonic-advanced/airsonic-advanced#794]
## Problem description

Playlists show songs as "Missing" after a full scan. If I click on the album link from the playlist and then go back to the playlist it's ok for that song or any other song from that same album.

### Steps to reproduce

Create a new playlist and add some random songs from different albums
Run a full scan from the Media Folders settings page or wait for the nightly scheduled scan.
Verify the playlist to show the "Missing" next to the songs

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220124042650
 * **Operating system**: Windows Server 2019
 * **Java version**: 17.0.1
 * **Proxy server**: HA Proxy on pfSense
 * **Client**: Brave , Chrome and Firefox
 * **Language**: English

## Additional notes

After playing around with this a bit I see that everytime I do anything with the playlist (add, star, remove), etc) I get several of these errors in the log :

2022-02-05 10:51:24.673 ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

java.lang.NullPointerException: Cannot invoke "org.airsonic.player.domain.Playlist.getId()" because "p" is null at org.airsonic.player.domain.Playlist.<init>(Playlist.java:61) ~[classes!/:11.0.0-SNAPSHOT] at org.airsonic.player.service.PlaylistService$BroadcastedPlaylist.<init>(PlaylistService.java:251) ~[classes!/:11.0.0-SNAPSHOT] at org.airsonic.player.ajax.PlaylistWSController.getPlaylist(PlaylistWSController.java:211) ~[classes!/:11.0.0-SNAPSHOT] at jdk.internal.reflect.GeneratedMethodAccessor338.invoke(Unknown Source) ~[na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na] at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:565) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:520) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:454) ~[spring-messaging-5.3.8.jar!/:5.3.8] at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.8.jar!/:5.3.8] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-02-05 10:52:17.539 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: 10 | EventType: REMOVED | Old value: org.airsonic.player.domain.Playlist@106e99fe | New value: null 2022-02-05 10:52:18.817 ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

**Comment by uSlackr** [comment]
I'm experiencing this issue.  My playlists show all tracks as MISSING.  I've verified the paths are correct.  FWIW, if I download the playlist it comes down empty, if I export it, the files are listed correctly in the m3u8 file. Importing it gives me a broken playlist.  Running in docker-compose on debian vm in proxmox.
pertinent compose entries
```
  airsonic:
    # image: airsonicadvanced/airsonic-advanced:edge-latest
    image: ghcr.io/kagemomiji/airsonic-advanced:edge-latest
    restart: unless-stopped
    container_name: sonic
    user: "1000"
    # links:
    #   - swag
    #depends_on:
    #  - swag
    environment:
      - TZ=America/New_York # e.g. Europe/London
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      # - JAVA_OPTS   #= "-DXmm300m" # For passing additional java options.
      # - CONTEXT_PATH # For setting url-base in reverse proxy setups.
    volumes:
      - /mnt/samba/Music/podcasts:/var/podcasts # Location of podcasts.
      - /mnt/samba/Music/playlists:/var/playlists # Location for playlists to be saved to.
      - /mnt/samba/Music:/var/music # Location of music.
      #
      #- /mnt/samba/TV:/var/media # Location of other media.
      - /data/airsonic:/var/airsonic # Configuration file location.
      # - /data/airsonic/airsonic.log:/var/airsonic/airsonic.log # Configuration file location.
    ports:
      - 4040:4040 # WebUI
     ```
