### ISSUE TITLE
Airsonic-advanced in docker-compose, and problems connecting postgresql database

### ISSUE THREAD

**Issue by bpalan** [airsonic-advanced/airsonic-advanced#888]
## Problem description

I ran Subsonic standalone under Ubuntu for about 10 years, but I'm new to airsonic-advanced and docker/docker-compose. I had lots of problems getting my first docker-compose.yml file to start, but was eventually able to get airsonic-advanced and postgresql containers setup and running. The site is up on http://LAN_IP:4040 and also through nginx on https://my.domain.name. I can see both containers start in airsonic.log, and I'm able to play files after the initial scan completes without issue.

Both containers start when I issue a docker-compose up command, but Airsonic is creating a native HSQLDB and not touching the running postgresql db. I also don't see any external db options configured in the Airsonic UI under Settings > Database.

Performing a new scan of my media folder of 450k files/12.4 TB takes ~6 hours. I couldn't even get the airsonic-advanced container to stay healthy during the initial HSQLDB scan without bumping up the available/maximum RAM in JAVA_OPTS.

I have also tried setting up spring_datasource and liquibase environment variables according to the formatting in the airsonic-advanced readme, but both docker-compose and yamllint would complain about the formatting of my yaml file when I removed the dashes as described.

### Steps to reproduce

1. Build containers with the attached docker-compose.yml
2. docker-compose up
3. postgresql db and airsonic-advanced start, but scanning the media folders creates the native HSQLDB.
 
## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220404145227
 * **Operating system**: Ubuntu 20.04.4
 * **Java version**: Java 14.0.2
 * **Proxy server**: nginx 1.18.0
 * **Client**: Chrome/Firefox
 * **Language**: English

## Additional notes

Docker-compose.yml:
```
---
version: '3.9'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - '/var/airsonic/postgresql/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  airsonic-advanced:
    image: 'airsonicadvanced/airsonic-advanced:latest'
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - spring_datasource_url:'jdbc:postgresql://db:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
      - spring_datasource_username:postgres
      - spring_datasource_password:postgres
      - spring_liquibase_parameters_userTableQuote:'"'
      - spring_datasource_hikari_connection_timeout:600000
      - JAVA_OPTS=-Dserver.forward-headers-strategy=NATIVE -Dairsonic.home=/var/airsonic
    volumes:
      - '/media/Music/lossless:/var/music'
      - '/media/Music/Podcast:/var/podcasts'
      - '/media/Music/playlist:/var/playlist'
      - '/var/airsonic:/var/airsonic'
    ports:
      - '4040:4040'
    depends_on:
      - db
    restart: always

```

Start of /var/airsonic/airsonic.log
```
Creating network "airsonic-advanced-docker_default" with the default driver
Creating airsonic-advanced-docker_db_1 ... done
Creating airsonic-advanced-docker_airsonic-advanced_1 ... done
Attaching to airsonic-advanced-docker_db_1, airsonic-advanced-docker_airsonic-advanced_1
airsonic-advanced_1  | Docker USER id: 0
airsonic-advanced_1  | Docker PUID env: 1001
airsonic-advanced_1  | Docker USER group: 0
airsonic-advanced_1  | Docker PGID env: 1001
db_1                 |
db_1                 | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1                 |
db_1                 | 2022-04-17 03:37:05.608 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1                 | 2022-04-17 03:37:05.608 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                 | 2022-04-17 03:37:05.608 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1                 | 2022-04-17 03:37:05.617 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                 | 2022-04-17 03:37:05.626 UTC [26] LOG:  database system was shut down at 2022-04-17 03:36:49 UTC
db_1                 | 2022-04-17 03:37:05.632 UTC [1] LOG:  database system is ready to accept connections
airsonic-advanced_1  | Process will run as:
airsonic-advanced_1  | User: 1001
airsonic-advanced_1  | Group: 1001
airsonic-advanced_1  | openjdk 14.0.2 2020-07-14
airsonic-advanced_1  | OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
airsonic-advanced_1  | OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
airsonic-advanced_1  | JAVA_OPTS=-Dserver.forward-headers-strategy=NATIVE -Dairsonic.home=/var/airsonic -Xms8g -Xmx12g
airsonic-advanced_1  | ffmpeg version 4.4.1-3ubuntu1+20.04.sav0.3 Copyright (c) 2000-2021 the FFmpeg developers
airsonic-advanced_1  | built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
airsonic-advanced_1  | configuration: --prefix=/usr --extra-version=3ubuntu1+20.04.sav0.3 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdav1d --enable-libzimg --enable-crystalhd --enable-libmfx --enable-libsvtav1 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
airsonic-advanced_1  | libavutil      56. 70.100 / 56. 70.100
airsonic-advanced_1  | libavcodec     58.134.100 / 58.134.100
airsonic-advanced_1  | libavformat    58. 76.100 / 58. 76.100
airsonic-advanced_1  | libavdevice    58. 13.100 / 58. 13.100
airsonic-advanced_1  | libavfilter     7.110.100 /  7.110.100
airsonic-advanced_1  | libswscale      5.  9.100 /  5.  9.100
airsonic-advanced_1  | libswresample   3.  9.100 /  3.  9.100
airsonic-advanced_1  | libpostproc    55.  9.100 / 55.  9.100
airsonic-advanced_1  | curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
airsonic-advanced_1  | Release-Date: 2020-01-08
airsonic-advanced_1  | Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
airsonic-advanced_1  | Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
airsonic-advanced_1  | PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
airsonic-advanced_1  | CONTEXT_PATH=/
airsonic-advanced_1  |            _                       _
airsonic-advanced_1  |      /\   (_)                     (_)
airsonic-advanced_1  |     /  \   _ _ __  ___  ___  _ __  _  ___
airsonic-advanced_1  |    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
airsonic-advanced_1  |   / ____ \| | |   \__ \ (_) | | | | | (__
airsonic-advanced_1  |  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
airsonic-advanced_1  |
airsonic-advanced_1  |
airsonic-advanced_1  |
airsonic-advanced_1  |
airsonic-advanced_1  |
airsonic-advanced_1  | 2022-04-16 23:37:07.001  INFO --- org.airsonic.player.Application          : Starting Application using Java 14.0.2 on 1e61b58c25e8 with PID 1 (/app/WEB-INF/classes started by au in /var)
airsonic-advanced_1  | 2022-04-16 23:37:07.003  INFO --- org.airsonic.player.Application          : No active profile set, falling back to 1 default profile: "default"
```

**Comment by randomnicode** [comment]
> I have also tried setting up spring_datasource and liquibase environment variables according to the formatting in the airsonic-advanced readme, but both docker-compose and yamllint would complain about the formatting of my yaml file when I removed the dashes as described.

>  environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      - spring_datasource_url:'jdbc:postgresql://db:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
      - spring_datasource_username:postgres
      - spring_datasource_password:postgres
      - spring_liquibase_parameters_userTableQuote:'"'
      - spring_datasource_hikari_connection_timeout:600000
      - JAVA_OPTS=-Dserver.forward-headers-strategy=NATIVE -Dairsonic.home=/var/airsonic

The dashes are not optional, and this compose file has incorrect syntax. Please read more about the compose file spec, particularly the environment section [here](https://github.com/compose-spec/compose-spec/blob/master/spec.md#environment). You cannot mix and match `-` (which indicates array semantics to yaml parser) and `=` with non-dash (which indicates dictionary semantics) and `:`, which you are doing in this section

your environment section may look like this:
```
environment:
  PUID: 1001
  PGID: 1001
  TZ: America/New_York
  spring_datasource_url: 'jdbc:postgresql://db:5432/postgres?stringtype=unspecified&raiseExceptionOnSilentRollback=false'
  spring_datasource_username: postgres
  spring_datasource_password: postgres
  spring_liquibase_parameters_userTableQuote: '"'
  spring_datasource_hikari_connection_timeout: 600000
  JAVA_OPTS: '-Dserver.forward-headers-strategy=NATIVE -Dairsonic.home=/var/airsonic'
```

**Comment by dsmouse** [comment]
The way I got this to work is to add the JDBC string to the airsonic.properties file; as far as I can tell the environment wasn't honored, but it's been a few months since I hacked on that part.

**Comment by yllekz** [comment]
Mind if I ask why you are using a separate DB? Unless your song library is insanely huge, I don't really know why you'd want to add additional overhead.

To help out, here's what my docker-compose looks like. It uses no database aside from whatever internal system is being utilized by Airsonic itself:

```
version: "2.1"
services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - JAVA_OPTS=-Xmx256M #https://github.com/airsonic-advanced/airsonic-advanced/issues/903
    volumes:
      - /path/to/config/airsonic-advanced:/var/airsonic
      - /path/to/Music:/var/music:rw
      - /path/to/Music/Playlists/AirsonicAdvanced:/var/playlists:rw
      - /path/to/Podcasts/airsonic:/var/podcasts:rw
    ports:
      - 4041:4040/tcp #AirSonic Web UI Port
      #- 4041:4041/tcp #DLNA/UpnP Port
      #- 1900:1900/udp #DLNA/UpnP Port
    restart: unless-stopped
```
