### ISSUE TITLE
SubSonic API showing duplicate song entries under snapraid+mergerfs

### ISSUE THREAD

**Issue by lifehackerhansol** [airsonic-advanced/airsonic-advanced#904]
## Problem description

This only happens when using the API. The web client is working fine.
Every single track is duplicated when viewing the server via a playback client, i.e. Substreamer on Android. This happens on all of them, I tested multiple clients and multiple Android devices, even a Windows client for the sake of testing.

Screenshots as to what this looks like: 
[Substreamer](https://user-images.githubusercontent.com/37358975/167290387-0bc147eb-ceb7-4c56-ad28-1e291d35112c.png)
[Ultrasonic](https://user-images.githubusercontent.com/37358975/167290455-9227f13a-ddd7-4542-baf2-69b159e2332c.png)
[Clementine (Windows)](https://user-images.githubusercontent.com/37358975/167290669-5385c8e4-bb54-4e74-874e-954c0068b5cc.png)
[airsonic](https://user-images.githubusercontent.com/37358975/167290414-f3046156-2777-44e6-b60d-a4c4b7ac2908.png)
[the folder in question](https://user-images.githubusercontent.com/37358975/167290501-c898a252-3dd4-410f-b52e-23b6f136d955.png)

docker-compose is as follows:
```
version: "3"

services:
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - JAVA_OPTS='-Dserver.forward-headers-strategy=native'
    user: 1000:1000
    volumes:
      - ./data:/var/airsonic
      - /mnt/pool1/music/Music:/var/music
      - /mnt/pool1/music/Playlists:/var/playlists
      - /mnt/pool1/music/Podcasts:/var/podcasts
    ports:
      - 4040:4040
    restart: unless-stopped
```

### Steps to reproduce

1. Start airsonic
2. Log in from a local client of any sort
3. Check any album and compare to the web client

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220418221611 – April 18, 2022 at 3:16:11 PM PDT [Commit: [a5df18f2459362005a80af2903a6c5b23c8f194e](https://github.com/airsonic-advanced/airsonic-advanced/commit/a5df18f2459362005a80af2903a6c5b23c8f194e)]
 * **Operating system**: Ubuntu 22.04 64-bit, under Docker
 * **Java version**: whatever version the official Docker image is using
 * **Proxy server**: Caddy v2
 * **Client**: Microsoft Edge Windows 101.0.1210.39, Clementine 1.3.1, Substreamer 5.0.50 (Play Store), Ultrasonic 3.1.1 (Play Store)
 * **Language**: English

## Additional notes

All of this was set up today for the first time on this machine. So all docker images are latest as of this writing, and the database is freshly created. Probably as clean as it can get. No settings were touched aside from removing the default admin credential.
