### ISSUE TITLE
Index / Artist missing

### ISSUE THREAD

**Issue by kindlydodo** [airsonic-advanced/airsonic-advanced#914]
## Problem description

In the left sidebar, there are no Index A - Z, or Artists to choose. Its showing me only Albums. Generaly its realy wired. I dont know if this is normal. It doesnt look like in the Screenshot https://github.com/airsonic-advanced/airsonic-advanced/blob/master/contrib/assets/screenshot.png

Basicly i want to setup to look like in the screenshot above. I wanna be able to Browse by Artist.
Do i need to configure something special?

Here is a Screenshot of my instance right after the login:
![Bildschirmfoto von 2022-05-30 10-05-53](https://user-images.githubusercontent.com/66476800/170946983-ad89a874-5dbf-482f-a3e8-25d43a16fad4.png)

i am using docker latest

### Steps to reproduce

*Describe how somebody else could observe the same behavior you do. If possible,
include relevant configuration or files that cause the problem. If sharing media
files, ensure you are legally permitted to share copies!*

1. create docker-compose file and run it:
```
version: "3"
    services:
      airsonic-advanced:
        container_name: airsonic-advanced
        image: airsonicadvanced/airsonic-advanced:latest
        restart: unless-stopped
        ports: 
          - 4040:4040
          - 4041:4041 #UPnp
        environment:
          TZ: Europe/Zurich #optional - show logs in local timezone
          JAVA_OPTS: '-Dserver.forward-headers-strategy=native' #optional - if you use a reverse-proxy
          PUID: 1000
          PGID: 1000
        volumes:
          - /home/besc/tmp/airsonic/playlists:/var/playlists
          - /home/besc/tmp/airsonic/podcasts:/var/podcasts
          - /home/besc/tmp/airsonic/data:/var/airsonic
          - /home/besc/tmp/airsonic/music:/var/musicv
```
2. login as admin

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220418221611 – April 19, 2022 at 12:16:11 AM CEST [Commit: [a5df18f2459362005a80af2903a6c5b23c8f194e](https://github.com/airsonic-advanced/airsonic-advanced/commit/a5df18f2459362005a80af2903a6c5b23c8f194e)]
 * **Operating system**: Linux 5.13.0-44-generic #49~20.04.1-Ubuntu
 * **Java version**: Apache Tomcat/9.0.60, java 14.0.2, Linux (78.1 MB / 147.0 MB)
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* None
 * **Client**: firefox / chromium
 * **Language**: EN

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*
