### ISSUE TITLE
Can't access settings tab through reverse proxy by HTTPS (Mixed content error)

### ISSUE THREAD

**Issue by verybadsoldier** [airsonic-advanced/airsonic-advanced#939]
This is basically a reopening of this vanilla airsonic issue:
https://github.com/airsonic/airsonic/issues/789

So this is mostly a copy paste:

# Problem description
Can't access settings tab through reverse proxy over HTTPS. When clicked, the button does nothing, and no event is logged in the About tab. When control clicking or opening in a new tab, the tab opens without the rest of the surrounding interface. This does not happen when accessing the web interface from localhost:4040.

# Steps to reproduce
* Install airsonic-advanced and traefik via docker
* Login to the web interface through the proxy (through https)
* Click the settings button/tab: the interface doesn't change.

# System information
Airsonic version docker: airsonicadvanced/airsonic-advanced:edge-11.0.0-SNAPSHOT.20220625052932
Operating system: Ubuntu 22.04
Proxy server: traefik docker: traefik:v2.5.3
Client: Windows Chrome Version 104.0.5112.81 (Official Build) (64-Bit)

This is how the click on the Settings button looks like in Chrome network web developer:
![image](https://user-images.githubusercontent.com/364469/186258156-fa959686-cdea-4871-aa54-a3c79cde6afb.png)

I think the problem is that in the response header the target URL contains `http` while it should be `https` (which was used to access airsonic in the beginning).

So Chrome refuses to load data via HTTP when the page uses HTTPS with this error message:
```
Mixed Content: The page at 'https://airsonic.mysecretdomain.xyz/' was loaded over HTTPS, but requested an insecure frame 'http://airsonic.mysecretdomain.xyz/home.view'. This request has been blocked; the content must be served over HTTPS.
```

I tried the suggested solution from the original ticket to set `server.use-forward-headers=true` in airsonic.properties and also by adding `-Dserver.use-forward-headers=true` to the start parameters. But this didn't change the issue for me.

This is my docker-compose file:
```
version: "2.1"
services:
  app:
    image: airsonicadvanced/airsonic-advanced:edge-11.0.0-SNAPSHOT.20220625052932
    container_name: airsonic
    networks:
      - traefik_default
    environment:
      - JAVA_OPTS=-Dserver.use-forward-headers=true
    volumes:
      - ./playlists:/var/playlists
      - ./podcasts:/var/podcasts
      - ./data:/var/airsonic
      - /media/music:/var/music
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.router-airsonic.entrypoints=web-secure"
      - "traefik.http.routers.router-airsonic.rule=Host(`airsonic.mysecretdomain.xyz`)"
      - "traefik.http.routers.router-airsonic.tls.certresolver=letsencrypt"
      - "traefik.http.services.service-airsonic.loadbalancer.server.port=4040"

networks:
  traefik_default:
    external: true
```

Any ideas please? Thanks alot.
