### ISSUE TITLE
Docker Compose on start: ffmpeg libc.so.6: version GLIBC_2.34' not found

### ISSUE THREAD

**Issue by fwgx** [airsonic-advanced/airsonic-advanced#952]
## Problem description

Starting from docker-compose results in error `var/airsonic/transcode/ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34' not found (required by /var/airsonic/transcode/ffmpeg`:

Docker Compose file:
```
version: '3.1'

services:
  airsonic-adv: 
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-adv
    restart: always
    volumes:
      - ./volumes/data:/var/airsonic
      - ./volumes/music:/var/music
      - ./volumes/playlists:/var/playlists
      - ./volumes/podcasts:/var/podcasts
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4040:4040
```

Error log:

```airsonic-adv    | Docker USER id: 0
airsonic-adv    | Docker PUID env: 0
airsonic-adv    | Docker USER group: 0
airsonic-adv    | Docker PGID env: 0
airsonic-adv    | usermod: no changes
airsonic-adv    | Process will run as:
airsonic-adv    | User: 0
airsonic-adv    | Group: 0
airsonic-adv    | openjdk 14.0.2 2020-07-14
airsonic-adv    | OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
airsonic-adv    | OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
airsonic-adv    | JAVA_OPTS=
airsonic-adv    | /var/airsonic/transcode/ffmpeg: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34' not found (required by /var/airsonic/transcode/ffmpeg)
```

### Steps to reproduce

Run up the container using the above yml on Ubuntu 22.04.1 LTS and it errors immediately.

## System information

 * **Airsonic version**: *latest*
 * **Operating system**: *Ubuntu 22.04.1 on x64*
 * **Java version**: *openjdk 14.0.2 2020-07-14.*
 * **Proxy server**: N/A
 * **Client**: *N/A*
 * **Language**: *N/A*
