### ISSUE TITLE
docker-compose error while loading shared libraries: libavdevice.so.59

### ISSUE THREAD

**Issue by 46620** [airsonic-advanced/airsonic-advanced#963]
## Problem description

When starting airsonic-advanced through docker I get the following error (compose file and full log are at the bottom):

`/var/airsonic/transcode/ffmpeg: error while loading shared libraries: libavdevice.so.59: cannot open shared object file: No such file or directory`

### Steps to reproduce

1. Run `docker-compose up -d` or add it as a stack in portainer
2. Airsonic fails to load

## System information

 * **Airsonic version**: latest bleeding edge in docker (tagged airsonic-advanced:gitrun-2559573986)
 * **Operating system**: Docker on Debian host
 * **Proxy server**: nginx

## Additional notes

docker-compose.yml
```
version: "3"

services:
  airsonic-advanced:
    container_name: airsonic-advanced
    image: airsonicadvanced/airsonic-advanced:edge-latest
    restart: unless-stopped
    ports: 
      - 4040:4040
      - 4041:4041 #UPnp
    environment:
      - TZ=America/New_York
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native
      - PUID=1000
      - PGID=1000
    volumes:
      - /media/Music:/var/music
      - /opt/airsonic:/var/airsonic
      - /opt/airsonic/playlists:/var/playlists
      - /opt/airsonic/podcasts:/var/podcasts
```

Error log
```
Docker USER id: 0
Docker PUID env: 1000
Docker USER group: 0
Docker PGID env: 1000
usermod: no changes
Process will run as:
User: 1000
Group: 1000
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
JAVA_OPTS=-Dserver.forward-headers-strategy=native
/var/airsonic/transcode/ffmpeg: error while loading shared libraries: libavdevice.so.59: cannot open shared object file: No such file or directory
```
